---
web:
  hosts:
    web1:
      ansible_host: "{{ lookup('env', 'WEB1_HOST') }}"
      ansible_ssh_private_key_file: "{{ lookup('env', 'KEY') }}"
      ansible_user: "{{ lookup('env', 'ANSIBLE_USER') }}"
    web2:
      ansible_host: "{{ lookup('env', 'WEB2_HOST') }}"
      ansible_ssh_private_key_file: "{{ lookup('env', 'KEY') }}"
      ansible_user: "{{ lookup('env', 'ANSIBLE_USER') }}"